# Generated by Django 3.2.12 on 2022-09-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('level', models.IntegerField(blank=True, default=0)),
                ('good_count', models.IntegerField(blank=True, default=0)),
                ('sub_category_count', models.IntegerField(blank=True, default=0)),
                ('logo', models.ImageField(blank=True, upload_to='uploads')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
