# Generated by Django 3.2.12 on 2022-09-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('level', models.IntegerField(blank=True, default=0)),
                ('old_price', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('short_description', models.TextField(blank=True, max_length=200)),
                ('weight', models.TextField(blank=True, max_length=200)),
                ('dimension', models.TextField(blank=True, max_length=200)),
                ('materials', models.TextField(blank=True, max_length=200)),
                ('extra', models.TextField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('logo', models.ImageField(blank=True, upload_to='uploads')),
                ('logo2', models.ImageField(blank=True, upload_to='uploads')),
                ('logo3', models.ImageField(blank=True, upload_to='uploads')),
                ('logo4', models.ImageField(blank=True, upload_to='uploads')),
                ('logo5', models.ImageField(blank=True, upload_to='uploads')),
                ('logo6', models.ImageField(blank=True, upload_to='uploads')),
                ('logo_vertical', models.ImageField(blank=True, upload_to='uploads')),
                ('logo_horizontal', models.ImageField(blank=True, upload_to='uploads')),
                ('is_main', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_discount', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.size')),
            ],
        ),
    ]
