# Generated by Django 3.2.12 on 2022-09-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220917_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='good',
            name='stock',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
