# Generated by Django 4.1.2 on 2022-10-31 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cartitem_all_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='crated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 11, 19, 37, 41719)),
        ),
    ]
