# Generated by Django 4.1.2 on 2022-11-01 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_cart_crated_at_wishitem_compareitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='crated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 23, 8, 13, 9995)),
        ),
    ]
