# Generated by Django 4.1.2 on 2022-11-02 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_subscriber_alter_cart_crated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='crated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 0, 40, 2, 689515)),
        ),
    ]
